import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { TanStackProvider } from "./tanstack-provider";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ConditionalFooter from "@/components/footer/ConditionalFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        <Navbar />
        <TanStackProvider>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </TanStackProvider>
        <ConditionalFooter />
      </body>
    </html>
  );
}
